### ISSUE TITLE
value-ls Cargo.toml package version (and edition) out-of-sync with actual release

### ISSUE THREAD

**Issue by errantepiphany** [errata-ai/vale-ls#3]
Looking at the latest release:
https://github.com/errata-ai/vale-ls/blob/v0.3.5/Cargo.toml

Why in Cargo.toml, do I see this:
```toml
[package]
edition = "2021"
version = "0.1.0"
```
instead of this?
```toml
[package]
edition = "2023"
version = "0.3.5"
```

Shouldn't those values align with the version of vale-ls?

Background of how this came to my attention:

I'm using mason.nvim inside neovim to install LSP servers for me, and it is clearly downloading v0.3.5:
https://github.com/mason-org/mason-registry/blob/main/packages/vale-ls/package.yaml#L14

However when it reports upon the version of value-ls, 0.1.0 gets returned. This is very misleading, and makes you think you're using an ancient version of vale-ls.
